const $=id=>document.getElementById(id);let authMode='signup';
const samples={suspicious:'Absolutely amazing!!! Best product ever!!! You MUST buy this right now, it changed my life completely. Five stars!!!',genuine:'I have used this coffee grinder for about three weeks. It is quieter than my old one and the grind size is fairly consistent. The lid feels a little flimsy, but overall it is good value for the price.'};
const positive=['amazing','excellent','great','love','perfect','best','awesome','fantastic','happy','recommend','good','quality'],negative=['broken','poor','waste','bad','slow','disappointed','flimsy','issue','problem','return'];
function analyze(text){const t=text.toLowerCase(),words=t.match(/[a-z']+/g)||[],ex=(text.match(/!/g)||[]).length,caps=(text.match(/[A-Z]/g)||[]).length,pos=positive.filter(x=>t.includes(x)).length,neg=negative.filter(x=>t.includes(x)).length,superlatives=['best','ever','must','literally','life-changing'].filter(x=>t.includes(x)).length;let suspicion=0,signals=[];if(ex>=3){suspicion+=20;signals.push('High exclamation intensity')}if(superlatives){suspicion+=18;signals.push('Promotional or absolute language')}if(words.length<18){suspicion+=14;signals.push('Very short, low-detail review')}if(caps>Math.max(2,words.length*.12)){suspicion+=10;signals.push('Unusual capitalization')}if(pos>=3&&neg===0){suspicion+=10;signals.push('Only positive sentiment')}if(/\b(buy now|must buy|changed my life)\b/.test(t)){suspicion+=15;signals.push('Call-to-action phrasing')}const score=Math.round(Math.max(8,Math.min(98,74+Math.min(35,Math.max(0,words.length/2))-suspicion)));return{score,label:score>=68?'Likely genuine':score>=43?'Suspicious':'Likely fake',signals:signals.length?signals:['Balanced sentiment and natural phrasing'],words:words.length,sentiment:pos>=neg?'Positive':'Mixed / neutral'};}
function currentHistory(){return JSON.parse(localStorage.getItem('reviewlens_history')||'[]');}function saveHistory(item){const h=currentHistory();h.unshift({...item,time:new Date().toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})});localStorage.setItem('reviewlens_history',JSON.stringify(h.slice(0,20)));renderDashboard();}
function renderSingle(r){const color=r.label==='Likely fake'?'#d65c5c':r.label==='Suspicious'?'#e58d42':'#147d61';$('singleResult').innerHTML=`<div class="result-card"><div class="verdict"><div><span class="card-kicker">ASSESSMENT</span><h2 style="color:${color}">${r.label}</h2><p>Based on ${r.words} words · ${r.sentiment} sentiment</p></div><div class="score" style="color:${color}">${r.score}<small>/100 trust</small></div></div><div class="meter"><div class="meter-fill" style="width:${r.score}%;background:${color}"></div></div><div class="signal"><span>Language profile</span><b>${r.sentiment}</b></div><div class="signal"><span>Behavioral signals</span><b style="color:${color}">${r.signals.length} detected</b></div></div><div class="result-card"><h3>Why this score?</h3><ul>${r.signals.map((s,i)=>`<li><strong>${i+1}.</strong> ${s}</li>`).join('')}<li><strong>Note.</strong> This is a screening signal, not proof of reviewer intent.</li></ul></div>`;$('singleResult').classList.remove('hidden');}
function renderDashboard(){const h=currentHistory(),manual=h.filter(x=>x.type==='Review').length,urls=h.filter(x=>x.type==='Product').length,avg=h.length?Math.round(h.reduce((a,x)=>a+x.score,0)/h.length):'—';$('dashboardStats').innerHTML=`<div class="stat"><span>ANALYSES RUN</span><strong>${h.length}</strong></div><div class="stat"><span>AVERAGE TRUST SCORE</span><strong>${avg}${avg==='—'?'':'/100'}</strong></div><div class="stat"><span>PRODUCT SCANS</span><strong>${urls}</strong></div>`;$('historyList').innerHTML=h.length?h.map(x=>`<div class="review-row"><p><strong>${x.type}</strong><br><small>${x.title}</small><br><small>${x.time}</small></p><span class="tag ${x.label!=='Likely genuine'?'suspicious':''}">${x.label}</span><strong>${x.score}/100</strong></div>`).join(''):'<div class="history-empty">No analyses yet. Run a review or product scan and it will appear here.</div>';}
function showView(view){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$(view+'View').classList.remove('hidden');$('pageLabel').textContent=view==='dashboard'?'DASHBOARD':view==='single'?'SINGLE REVIEW':'PRODUCT URL';$('profileMenu').classList.add('hidden');if(view==='dashboard')renderDashboard();}
function openAuth(mode){authMode=mode;$('authModal').classList.remove('hidden');$('nameField').style.display=mode==='signup'?'block':'none';$('authTitle').innerHTML=mode==='signup'?'Start making<br><em>smarter calls.</em>':'Welcome<br><em>back.</em>';$('authSubtitle').textContent=mode==='signup'?'Create your free workspace to analyze reviews with clarity.':'Sign in to continue to your ReviewLens workspace.';$('authSubmitText').textContent=mode==='signup'?'Create account':'Sign in';$('switchPrompt').textContent=mode==='signup'?'Already have an account?':'New to ReviewLens?';$('switchAuth').textContent=mode==='signup'?'Sign in':'Create account';$('authError').textContent='';setTimeout(()=>$('emailField').focus(),50);}
function enterApp(){const u=JSON.parse(localStorage.getItem('reviewlens_user')||'{}');localStorage.setItem('reviewlens_session','active');$('landing').classList.add('hidden');$('app').classList.remove('hidden');$('authModal').classList.add('hidden');const name=u.name||u.email?.split('@')[0]||'Review user',initial=name.charAt(0).toUpperCase();$('profileInitial').textContent=initial;$('menuInitial').textContent=initial;$('profileName').textContent=name;$('menuName').textContent=name;$('menuEmail').textContent=u.email||'Local account';renderDashboard();}
document.querySelectorAll('[data-auth]').forEach(b=>b.addEventListener('click',()=>openAuth(b.dataset.auth)));document.querySelectorAll('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>$('authModal').classList.add('hidden')));$('switchAuth').onclick=()=>openAuth(authMode==='signup'?'signin':'signup');$('authForm').onsubmit=e=>{e.preventDefault();const email=$('emailField').value.trim().toLowerCase(),pass=$('passwordField').value,existing=JSON.parse(localStorage.getItem('reviewlens_user')||'null');if(pass.length<8){$('authError').textContent='Use at least 8 characters for your password.';return}if(authMode==='signup'){localStorage.setItem('reviewlens_user',JSON.stringify({name:$('nameField').value.trim()||email.split('@')[0],email,password:pass}));enterApp();}else if(!existing||existing.email!==email||existing.password!==pass){$('authError').textContent='Incorrect email or password. Please try again.';}else enterApp();};
$('profileBtn').onclick=e=>{e.stopPropagation();$('profileMenu').classList.toggle('hidden');};document.addEventListener('click',e=>{if(!$('profileMenu').contains(e.target)&&e.target!==$('profileBtn'))$('profileMenu').classList.add('hidden');});document.querySelectorAll('.profile-menu-item[data-menu-view]').forEach(b=>b.onclick=()=>showView(b.dataset.menuView));$('menuLogout').onclick=()=>{$('logoutBtn').click();};$('logoutBtn').onclick=()=>{localStorage.removeItem('reviewlens_session');$('app').classList.add('hidden');$('landing').classList.remove('hidden');$('profileMenu').classList.add('hidden');};
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.scroll).scrollIntoView());$('reviewInput').oninput=()=>$('charCount').textContent=`${$('reviewInput').value.length} characters`;$('sampleBtn').onclick=()=>{$('reviewInput').value=samples.suspicious;$('reviewInput').dispatchEvent(new Event('input'));};$('analyzeBtn').onclick=()=>{const t=$('reviewInput').value.trim();if(!t){$('reviewInput').focus();return}const r=analyze(t);renderSingle(r);saveHistory({type:'Review',title:t.slice(0,58)+(t.length>58?'…':''),label:r.label,score:r.score});};
$('urlBtn').onclick=()=>{const url=$('urlInput').value.trim();if(!url){$('urlInput').focus();return}const demo=[samples.genuine,samples.suspicious,'The packaging was neat and delivery arrived on time. The product works as described, though setup instructions could be clearer.'],rs=demo.map(analyze),avg=Math.round(rs.reduce((a,b)=>a+b.score,0)/rs.length);$('urlResult').innerHTML=`<div class="url-summary"><div class="stat"><span>PRODUCT TRUST SCORE</span><strong>${avg}/100</strong></div><div class="stat"><span>REVIEWS SCANNED</span><strong>${demo.length}</strong></div><div class="stat"><span>FLAGGED SIGNALS</span><strong>${rs.filter(x=>x.label!=='Likely genuine').length}</strong></div></div><div class="table-card"><h3>Review pattern breakdown</h3>${rs.map((r,i)=>`<div class="review-row"><p>Review ${i+1}<br><small>${r.signals[0]}</small></p><span class="tag ${r.label!=='Likely genuine'?'suspicious':''}">${r.label}</span><strong>${r.score}/100</strong></div>`).join('')}</div>`;$('urlResult').classList.remove('hidden');saveHistory({type:'Product',title:url,label:avg>=68?'Likely genuine':avg>=43?'Suspicious':'Likely fake',score:avg});};$('clearHistory').onclick=()=>{localStorage.removeItem('reviewlens_history');renderDashboard();};
async function analyzeThroughApi(text){try{const response=await fetch('http://127.0.0.1:8765/api/analyze-review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});if(!response.ok)throw new Error('API error');return await response.json();}catch(error){const local=analyze(text);return {...local,trustScore:local.score,confidence:0,model:'browser-fallback',apiUnavailable:true};}}
$('analyzeBtn').onclick=async()=>{const t=$('reviewInput').value.trim();if(!t){$('reviewInput').focus();return}const button=$('analyzeBtn');button.disabled=true;button.innerHTML='Analyzing…';const r=await analyzeThroughApi(t);r.score=r.trustScore??r.score;renderSingle(r);saveHistory({type:'Review',title:t.slice(0,58),label:r.label,score:r.score});button.disabled=false;button.innerHTML='Analyze review <span>→</span>';};
// Replace the original demo form handler with persistent account validation.
function savedAccounts(){const list=JSON.parse(localStorage.getItem('reviewlens_accounts')||'[]');const legacy=JSON.parse(localStorage.getItem('reviewlens_user')||'null');if(legacy&&!list.some(x=>x.email===legacy.email))list.push(legacy);return list;}
$('authForm').onsubmit=e=>{e.preventDefault();const email=$('emailField').value.trim().toLowerCase(),pass=$('passwordField').value,accounts=savedAccounts();if(pass.length<8){$('authError').textContent='Use at least 8 characters for your password.';return}if(authMode==='signup'){if(accounts.some(x=>x.email===email)){$('authError').textContent='This email address already exists. Try signing in instead.';return}const account={name:$('nameField').value.trim()||email.split('@')[0],email,password:pass};accounts.push(account);localStorage.setItem('reviewlens_accounts',JSON.stringify(accounts));localStorage.setItem('reviewlens_user',JSON.stringify(account));enterApp();}else{const account=accounts.find(x=>x.email===email);if(!account){$('authError').textContent='No account found for this email address.';return}if(!account.password){$('authError').textContent='This older demo account needs to be created again with a password.';return}if(account.password!==pass){$('authError').textContent='Incorrect email or password. Please try again.';return}localStorage.setItem('reviewlens_user',JSON.stringify(account));enterApp();}};
async function updateModelStatus(){try{const response=await fetch('http://127.0.0.1:8765/api/health');document.querySelectorAll('.model-status').forEach(x=>{x.classList.toggle('online',response.ok);x.innerHTML=response.ok?'<i></i> Trained API connected':'<i></i> Browser fallback'});}catch(e){document.querySelectorAll('.model-status').forEach(x=>x.innerHTML='<i></i> Browser fallback');}}
function addModelStatus(){const host=document.querySelector('.sidebar-foot div:last-child');if(!host||host.querySelector('.model-status'))return;const node=document.createElement('span');node.className='model-status';node.innerHTML='<i></i> Checking model…';host.appendChild(node);const singleNav=document.querySelector('.nav-item[data-view="single"]');if(singleNav){singleNav.classList.add('new-analysis-nav');singleNav.innerHTML='<span>＋</span> New analysis';}const hero=document.querySelector('#dashboardView .dashboard-hero>div:first-child');if(hero&&!document.getElementById('newAnalysisHero')){const button=document.createElement('button');button.id='newAnalysisHero';button.className='primary new-analysis-hero';button.innerHTML='+ New analysis <span>→</span>';button.onclick=()=>showView('single');hero.appendChild(button);}}
function updateModelStatus(){addModelStatus();fetch('http://127.0.0.1:8765/api/health').then(r=>{document.querySelectorAll('.model-status').forEach(x=>{x.classList.toggle('online',r.ok);x.innerHTML=r.ok?'<i></i> Trained API connected':'<i></i> Browser fallback';});}).catch(()=>document.querySelectorAll('.model-status').forEach(x=>x.innerHTML='<i></i> Browser fallback'));}
if(localStorage.getItem('reviewlens_session')==='active')enterApp();addModelStatus();updateModelStatus();

// History UX: compact rows, delete actions, and reopening the saved report.
function renderDashboard(){const h=currentHistory(),urls=h.filter(x=>x.type==='Product').length,avg=h.length?Math.round(h.reduce((a,x)=>a+x.score,0)/h.length):'—';$('dashboardStats').innerHTML=`<div class="stat"><span>ANALYSES RUN</span><strong>${h.length}</strong></div><div class="stat"><span>AVERAGE TRUST SCORE</span><strong>${avg}${avg==='—'?'':'/100'}</strong></div><div class="stat"><span>PRODUCT SCANS</span><strong>${urls}</strong></div>`;$('historyList').innerHTML=h.length?h.map((x,i)=>`<div class="review-row history-item" data-history-index="${i}"><p><strong>${x.type}</strong><br><small class="history-title">${x.title}</small><br><small>${x.time}</small></p><span class="tag ${x.label!=='Likely genuine'?'suspicious':''}">${x.label}</span><strong>${x.score}/100</strong><button class="delete-history" data-delete-index="${i}" title="Delete analysis" aria-label="Delete analysis">×</button></div>`).join(''):'<div class="history-empty">No analyses yet. Run a review or product scan and it will appear here.</div>';}
function newReview(){showView('single');$('reviewInput').value='';$('charCount').textContent='0 characters';$('singleResult').classList.add('hidden');$('reviewInput').focus();}
function initHistoryActions(){const sample=$('sampleBtn');if(sample&&!$('newReviewBtn')){const plus=document.createElement('button');plus.id='newReviewBtn';plus.className='new-review-icon';plus.title='Start a new analysis';plus.setAttribute('aria-label','Start a new analysis');plus.textContent='＋';plus.onclick=newReview;sample.parentElement.insertBefore(plus,sample);}const list=$('historyList');if(list&&!list.dataset.bound){list.dataset.bound='1';list.onclick=e=>{const del=e.target.closest('[data-delete-index]');if(del){const h=currentHistory();h.splice(Number(del.dataset.deleteIndex),1);localStorage.setItem('reviewlens_history',JSON.stringify(h));renderDashboard();return}const row=e.target.closest('[data-history-index]');if(!row)return;const item=currentHistory()[Number(row.dataset.historyIndex)];if(item.type==='Review'&&item.text){showView('single');$('reviewInput').value=item.text;$('reviewInput').dispatchEvent(new Event('input'));if(item.report)renderSingle(item.report);}else if(item.type==='Product'){showView('url');$('urlInput').value=item.title;}};}}
const originalRenderSingle=renderSingle;renderSingle=function(r){window.lastReviewReport=r;originalRenderSingle(r);};const oldSaveHistory=saveHistory;saveHistory=function(item){oldSaveHistory({...item,text:item.text||item.title,report:item.report||window.lastReviewReport||null});};
const historyStyle=document.createElement('style');historyStyle.textContent='.sample-actions{display:flex;align-items:center;gap:8px}.new-review-icon{width:34px;height:34px;border:1px solid #d7e8df;background:#e8f8f0;color:#147d61;border-radius:9px;font-size:22px;line-height:1;cursor:pointer}.new-review-icon:hover{background:#c9f0dd}.dashboard-history{overflow:hidden}.history-item{grid-template-columns:minmax(0,1fr) auto 78px 30px;align-items:center}.history-item p{min-width:0;overflow:hidden}.history-title{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:100%}.delete-history{width:26px;height:26px;border:0;border-radius:7px;background:#fff0f0;color:#c75b5b;font-size:19px;line-height:20px;cursor:pointer}.delete-history:hover{background:#ffdcdc}@media(max-width:800px){.history-item{grid-template-columns:minmax(0,1fr) auto 55px 26px}.history-item .tag{font-size:9px}.profile-menu{right:-45px}}';document.head.appendChild(historyStyle);
setTimeout(initHistoryActions,0);

// Final workspace polish: keep the new-analysis control beside the sample action.
initHistoryActions=function(){
  const sample=$('sampleBtn');
  if(sample&&!sample.parentElement.classList.contains('sample-actions')){
    const group=document.createElement('div');group.className='sample-actions';
    const plus=$('newReviewBtn')||document.createElement('button');plus.id='newReviewBtn';plus.className='new-review-icon';plus.title='Start a new analysis';plus.setAttribute('aria-label','Start a new analysis');plus.textContent='＋';plus.onclick=newReview;
    sample.parentElement.insertBefore(group,sample);group.appendChild(plus);group.appendChild(sample);
  }
  const singleNav=document.querySelector('.nav-item[data-view="single"]');if(singleNav)singleNav.innerHTML='<span>◉</span> Text analysis';
  const list=$('historyList');if(list&&!list.dataset.bound){list.dataset.bound='1';list.onclick=e=>{const del=e.target.closest('[data-delete-index]');if(del){const h=currentHistory();h.splice(Number(del.dataset.deleteIndex),1);localStorage.setItem('reviewlens_history',JSON.stringify(h));renderDashboard();return}const row=e.target.closest('[data-history-index]');if(!row)return;const item=currentHistory()[Number(row.dataset.historyIndex)];if(item.type==='Review'&&item.text){showView('single');$('reviewInput').value=item.text;$('reviewInput').dispatchEvent(new Event('input'));if(item.report)renderSingle(item.report);}else if(item.type==='Product'){showView('url');$('urlInput').value=item.text||item.title;}};}
};
setTimeout(initHistoryActions,10);
function personalizeUrlPage(){const view=$('urlView');if(!view)return;const pill=view.querySelector('.dashboard-hero .pill'),title=view.querySelector('.dashboard-hero h1'),copy=view.querySelector('.dashboard-hero p'),metric=view.querySelector('.big-number'),metricLabel=view.querySelector('.big-number span'),notice=view.querySelector('.notice');if(pill)pill.textContent='PRODUCT REVIEW INTELLIGENCE';if(title)title.innerHTML='Understand the trust<br><em>behind every review.</em>';if(copy)copy.textContent='Analyze every review on a product page to find genuine experiences, suspicious patterns, and high-risk review signals.';if(metric)metric.firstChild.textContent='3';if(metricLabel)metricLabel.textContent='review signals tracked';if(notice)notice.remove();}
setTimeout(personalizeUrlPage,20);
const sectionLabelStyle=document.createElement('style');sectionLabelStyle.textContent='.app .dashboard-hero .pill{display:none!important}';document.head.appendChild(sectionLabelStyle);
setInterval(()=>{const single=$('singleView'),label=$('pageLabel');if(single&&label&&!single.classList.contains('hidden'))label.textContent='TEXT ANALYSIS';},100);
const polishStyle=document.createElement('style');polishStyle.textContent='.privacy{display:none!important}.view{padding-top:0!important}.topbar{margin-bottom:0}.profile-button{align-items:center;line-height:1}.profile-button .chevron{display:none!important}.sidebar-foot{display:none!important}.review-dashboard{padding-top:0!important}.landing-footer{display:flex!important}.sample-actions{display:flex;align-items:center;gap:8px}.new-url-icon{display:inline-grid;place-items:center;width:34px;height:34px;border:1px solid #d7e8df;background:#e8f8f0;color:#147d61;border-radius:9px;font-size:22px;font-weight:500;cursor:pointer}.new-url-icon:hover{background:#c9f0dd}.card-head> .sample-actions{margin-top:-2px}';document.head.appendChild(polishStyle);
